<?php 

return [
    'prepare' => [
        'grate',
        'layer',
        'level',
        'pinch',
        'pour',
        'scramble',
        'slice',
        'spread',
        'stir',
        'add',
        'blend',
        'bread',
        'chop',
        'cut',
        'dip',
    ],
    'prepared' => [
        'grated',
        'layered',
        'leveled',
        'pinched',
        'poured',
        'scrambled',
        'sliced',
        'spread',
        'stired',
        'added',
        'blended',
        'breaded',
        'chopped',
        'cut',
        'dipped',
    ],
    
    'cook' => [
        'cook',
        'bake',
        'melt',
        'grill',
        'simmer',
        'boil',
        'broil',
        'fry',
    ],
    'cooked' => [
        'cooked',
        'baked',
        'melted',
        'grilled',
        'simmered',
        'boiled',
        'broiled',
        'fried',
    ],
    
    'serve' => [
        'serve',
        'taste',
        'eat',
    ]
];