version: '2'

services:

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - ./:/recipeland
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: php:7.1.14-fpm
        restart: unless-stopped
        container_name: recipeland_php # Name used to run phpunit via ./recipe taste
        command: >
            bash -c "./vendor/bin/phinx migrate && 
                     ./vendor/bin/phinx seed:run"
        volumes:
            - ./:/var/www/html
        links:
            - postgres
            - redis
        depends_on:
            - composer

    composer:
        image: composer:1.6.3
        restart: 'no'
        command: install
        volumes:
            - .:/app

    postgres:
        image: postgres:9.6.7-alpine
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh

    redis:
        image: redislabs/redisearch:1.0.8
        restart: unless-stopped
        ports:
            - "6379:6379"