version: '2'

services:

    nginx:
        image: nginx:latest
        container_name: recipeland_nginx
        restart: on-failure
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        volumes:
            - ./:/recipeland
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        image: rafaelbeckel/php-72-fpm-pdo-pgsql
        restart: on-failure
        container_name: recipeland_php # Name used to run phpunit via ./recipe taste
        command: >
            bash -c "./vendor/bin/phinx migrate && 
                     ./vendor/bin/phinx seed:run"
        volumes:
            - ./:/var/www/html
        depends_on:
            - composer
            - postgres
            - redis

    composer:
        image: composer:1.6.3
        container_name: recipeland_composer
        restart: on-failure
        command: install
        volumes:
            - .:/app

    postgres:
        image: postgres:9.6.7-alpine
        container_name: recipeland_postgres
        restart: on-failure
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgres:/docker-entrypoint-initdb.d
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_MULTIPLE_DATABASES: hellofresh,hellofresh_test

    redis:
        image: redislabs/redisearch:1.0.8
        container_name: recipeland_redis
        restart: on-failure
        ports:
            - "6379:6379"
