version: '2'

services:

    nginx:
        image: nginx:alpine
        container_name: recipeland_nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/recipeland
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - recipeland

    php:
        image: rafaelbeckel/php-72-fpm-pdo-pgsql
        restart: always
        container_name: recipeland_php # Name used to run phpunit via ./recipe taste
        # command: >
        #     bash -c "./vendor/bin/phinx migrate && 
        #              ./vendor/bin/phinx seed:run"
        expose:
            - "9000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - composer
            - postgres
            - redis
        networks:
            - recipeland
            - data

    composer:
        image: composer:1.6.3
        container_name: recipeland_composer
        restart: on-failure
        command: install
        volumes:
            - .:/app
        networks:
            - recipeland

    postgres:
        image: postgres:9.6.7-alpine
        container_name: recipeland_postgres
        restart: on-failure
        expose:
            - "5432"
        volumes:
            - ./docker/postgres:/docker-entrypoint-initdb.d
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_DB: hellofresh
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_MULTIPLE_DATABASES: hellofresh_test
        networks:
            - data

    redis:
        image: redislabs/redisearch:1.0.8
        container_name: recipeland_redis
        restart: on-failure
        expose:
            - "6379"
        networks:
            - data

networks:
    recipeland:
        driver: bridge
    data:
        driver: bridge
